- name: Install Ansible Python 2 Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-firewall
    - libselinux-python
    - libsemanage-python
    - wireless-tools

- name: Development Environment
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - jq
    - kubernetes-client
    - google-chrome-beta
    - gnome-tweak-tool
    - paper-icon-theme
    - paper-gtk-theme
    - xorg-x11-utils
    - akmod-VirtualBox VirtualBox

- name: Remove PackageKit
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - PackageKit
