----
- name: Update Package List
  command: dnf --refresh check-update
  args:
    warn: no
  register: updates_available
  failed_when: (updates_available.rc != 0) and
               (updates_available.rc != 100)
  changed_when: false

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- include: dependencies.yml
- include: codecs.yml
- include: repo.yml
