---
- name: Update Package List
  command: dnf --refresh check-update
  args:
    warn: no
  register: updates_available
  failed_when: (updates_available.rc != 0) and
               (updates_available.rc != 100)
  changed_when: false

- include: repo.yml
- include: dependencies.yml
- include: codecs.yml
- include: messaging.yml
- include: nfs.yml
- include: gnome.yml
