- name: Google Linux signing key
  rpm_key:
    state: present
    key: https://dl.google.com/linux/linux_signing_key.pub

- name: Oracle Virtual Box signing key.
  rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc

- name: Docker signing key.
  rpm_key:
    state: present
    key: https://yum.dockerproject.org/gpg

- name: RPM Fusion Free and Non-Free
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_current }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_current }}.noarch.rpm
