- name: Install Ansible Python 2 Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
#    - python-firewall
    - libselinux-python
    - libsemanage-python

- name: Additional Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - p7zip

- name: Ensure NFS utilities are installed.
  package:
    name: nfs-utils
    state: installed

- name: Make sure nginx is installed
  package:
    name: nginx
    state: present

- name: nginx proxy configurations
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - kodi.conf
    - media.conf

- name: Make sure private directory exists
  file:
    state: directory
    path: /etc/ssl/certs/private/
    owner: root
    group: root
    mode: 0775

- name: Copy latest certificate
  copy:
    src: ./.secrets/fullchain.pem
    dest: /etc/ssl/certs/private/cert.crt
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Copy latest private keys
  copy:
    src: ./.secrets/privkey.pem
    dest: /etc/ssl/certs/private/cert.key
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Install PowerPanel CyperPower UPS
  package:
    name: https://dl4jz3rbrsfum.cloudfront.net/software/powerpanel-132-0x86_64.rpm
    state: installed

- name: PowerPanel service is enabled
  service:
    name: pwrstatd
    state: started
    enabled: yes
