---
- name: mount all
  command: mount -a
  args:
    warn: no

- name: restart kodi
  service:
    name: kodi
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
