- include_tasks: nfs.yml

- name: Copy advanced settings file.
  template:
    src: advancedsettings.xml.j2
    dest: /home/osmc/.kodi/userdata/advancedsettings.xml
    owner: root
    group: root
    mode: 0644

- name: ll alias
  lineinfile:
    path: /etc/bash.bashrc
    regexp: '^alias ll="ls -l"'
    line: 'alias ll="ls -l"'

- name: Ensure nginx utilities is installed.
  package:
    name: nginx
    state: installed

- name: Generate Diffie–Hellman primes
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  args:
    creates: /etc/ssl/certs/dhparam.pem

- name: Copy default http-https redirect
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0644

- name: Copy proxy
  template:
    src: proxy.j2
    dest: /etc/nginx/sites-enabled/proxy
    owner: root
    group: root
    mode: 0644

- name: Make sure private directory exists
  file:
    state: directory
    path: /etc/ssl/certs/private/
    owner: root
    group: root
    mode: 0775

- name: Copy latest certificate
  copy:
    src: ./.secrets/fullchain.pem
    dest: /etc/ssl/certs/private/cert.crt
    owner: root
    group: root
    mode: 0644

- name: Copy latest private keys
  copy:
    src: ./.secrets/privkey.pem
    dest: /etc/ssl/certs/private/cert.key
    owner: root
    group: root
    mode: 0644

- name: Start nginx
  service:
    name: nginx
    state: restarted
