- include: nfs.yml

- name: Copy advanced settings file.
  template:
    src: advancedsettings.xml.j2
    dest: /home/osmc/.kodi/userdata/advancedsettings.xml
    owner: root
    group: root
    mode: 0644

- name: Ensure nginx utilities is installed.
  package:
    name: nginx
    state: installed

- name: Generate Diffie–Hellman primes
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  args:
    creates: /etc/ssl/certs/dhparam.pem

- name: Copy default http-https redirect
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0644

- name: Copy proxy
  template:
    src: proxy.j2
    dest: /etc/nginx/sites-enabled/proxy
    owner: root
    group: root
    mode: 0644

- name: Start nginx
  service:
    name: nginx
    state: restarted
