- include_tasks: nfs.yml

- name: Copy advanced settings file.
  template:
    src: advancedsettings.xml.j2
    dest: /home/osmc/.kodi/userdata/advancedsettings.xml
    owner: osmc
    group: osmc
    mode: 0644

- name: Create addicted configuration directory
  file:
    name: /home/osmc/.kodi/userdata/addon_data/service.subtitles.rvm.addic7ed/
    state: directory
    owner: osmc
    group: osmc
    mode: 0755

- name: Copy addicted settings file.
  template:
    src: addic7ted.xml.j2
    dest: /home/osmc/.kodi/userdata/addon_data/service.subtitles.rvm.addic7ed/settings.xml
    owner: osmc
    group: osmc
    mode: 0644

- name: Create opensubtitles configuration directory
  file:
    name: /home/osmc/.kodi/userdata/addon_data/service.subtitles.opensubtitles/
    state: directory
    owner: osmc
    group: osmc
    mode: 0755

- name: Copy opensubtitles settings file.
  template:
    src: opensubtitles.xml.j2
    dest: /home/osmc/.kodi/userdata/addon_data/service.subtitles.opensubtitles/settings.xml
    owner: osmc
    group: osmc
    mode: 0644

- name: Create specialfeatures configuration directory
  file:
    name: /home/osmc/.kodi/userdata/addon_data/plugin.video.specialfeatures/
    state: directory
    owner: osmc
    group: osmc
    mode: 0755

- name: Copy specialfeatures settings file.
  template:
    src: specialfeatures.xml.j2
    dest: /home/osmc/.kodi/userdata/addon_data/plugin.video.specialfeatures/settings.xml
    owner: osmc
    group: osmc
    mode: 0644

# Dumb hack since it won't properly take the hostname.
- name: specialfeatures hack
  lineinfile:
    path: /home/osmc/.kodi/addons/plugin.video.specialfeatures/lib/sys_init.py
    regexp: '^ipadd = addon'
    line: "ipadd = \"{{mysql_hostname}}\""

- name: Create skin configuration directory
  file:
    name: /home/osmc/.kodi/userdata/addon_data/skin.estuary/
    state: directory
    owner: osmc
    group: osmc
    mode: 0755

- name: Skin settings
  copy:
    dest: /home/osmc/.kodi/userdata/addon_data/skin.estuary/settings.xml
    src: skin.estuary.xml
    group: osmc
    owner: osmc
    mode: 0644

- name: ll alias
  lineinfile:
    path: /etc/bash.bashrc
    regexp: '^alias ll="ls -l"'
    line: 'alias ll="ls -l"'

- name: osmc remote enter key
  lineinfile:
    path: /etc/lirc/osmc-remote-lircd.conf
    regexp: '^\s+KEY_.*0x14$'
    line: '          KEY_ENTER                0x14'

- name: Ensure nginx utilities is installed.
  package:
    name: nginx
    state: present

- name: Generate Diffie–Hellman primes
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  args:
    creates: /etc/ssl/certs/dhparam.pem

- name: Copy default http-https redirect
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Copy proxy
  template:
    src: proxy.j2
    dest: /etc/nginx/sites-enabled/proxy
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Make sure private directory exists
  file:
    state: directory
    path: /etc/ssl/certs/private/
    owner: root
    group: root
    mode: 0775

- name: Copy latest certificate
  copy:
    src: "{{cert_fullchain}}"
    dest: /etc/ssl/certs/private/cert.crt
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Copy latest private keys
  copy:
    src: "{{cert_privkey}}"
    dest: /etc/ssl/certs/private/cert.key
    owner: root
    group: root
    mode: 0644
  notify: restart nginx