- name: Make sure movie directory exists
  file:
    path: "/storage/mnt/movies"
    state: directory

- name: Movies mount
  lineinfile:
    path: /etc/fstab
    regexp: "{{movie_mount_regex}}"
    line: "{{movie_nfs_mount}}"
  notify: mount all

- name: Make sure tv directory exists
  file:
    path: "/storage/mnt/tv"
    state: directory

- name: TV mount
  lineinfile:
    path: /etc/fstab
    regexp: "{{tv_mount_regex}}"
    line: "{{tv_nfs_mount}}"
  notify: mount all
