- name: Make sure private directory exists
  file:
    state: directory
    path: /etc/ssl/certs/private/
    owner: root
    group: ssl-cert
    mode: 0770

- name: Make sure site directory exists
  file:
    state: directory
    path: /usr/lib/unifi/data/sites/default
    owner: unifi
    group: unifi
    mode: 0770

- name: Copy config.gateway.json
  template:
    src: config.gateway.json.j2
    dest: /usr/lib/unifi/data/sites/default/config.gateway.json
    owner: unifi
    group: unifi
    mode: 0644
  notify:
    - restart unifi

- name: Copy latest certificate
  copy:
    src: "{{cert_fullchain}}"
    dest: /etc/ssl/certs/private/cert.crt
    force: yes
    owner: root
    group: ssl-cert
    mode: 0644
  notify:
    - restart nginx

- name: Copy latest private keys
  copy:
    src: "{{cert_privkey}}"
    dest: /etc/ssl/certs/private/cert.key
    force: yes
    owner: root
    group: ssl-cert
    mode: 0640
  notify:
    - restart nginx
  register: new_private_keys

- name: Generate PKCS#12 file
  openssl_pkcs12:
    action: export
    path: /etc/ssl/private/unifi.p12
    friendly_name: "unifi"
    passphrase: aircontrolenterprise
    privatekey_path: /etc/ssl/certs/private/cert.key
    certificate_path: /etc/ssl/certs/private/cert.crt
    mode: 0640
    state: present
  when: new_private_keys.changed

- name: Make sure SSL keystore has correct permissions
  file:
    path: /etc/ssl/private/unifi.keystore.jks
    owner: root
    group: ssl-cert
    mode: 0640

- name: Import SSL into keystore
  command:
    chdir: /etc/ssl/private/
    argv:
      - keytool
      - -noprompt
      - -importkeystore
      - -srckeystore
      - unifi.p12
      - -srcstoretype
      - PKCS12
      - -srcstorepass
      - aircontrolenterprise
      - -destkeystore
      - unifi.keystore.jks
      - -storepass
      - aircontrolenterprise
  notify:
    - restart unifi
  when: new_private_keys.changed
