- name: Copy mount file.
  template:
    src: storage-mnt.mount.j2
    dest: /storage/.config/system.d/storage-mnt.mount
    owner: root
    group: root
    mode: 0644
  notify:
    - mount all

- name: Copy advanced settings file.
  template:
    src: advancedsettings.xml.j2
    dest: /storage/.kodi/userdata/advancedsettings.xml
    owner: root
    group: root
    mode: 0644
  notify:
    - restart kodi

- name: Generate Diffie–Hellman primes
  command: openssl dhparam -out /storage/.kodi/userdata/addon_data/docker.linuxserver.nginx/config/keys/dhparam.pem 4096
  args:
    creates: /storage/.kodi/userdata/addon_data/docker.linuxserver.nginx/config/keys/dhparam.pem

- name: Copy default http-https redirect
  template:
    src: default.j2
    dest: /storage/.kodi/userdata/addon_data/docker.linuxserver.nginx/config/nginx/site-confs/default
    owner: root
    group: root
    mode: 0644

- name: Change permissions on keys folder.
  file:
    path: /storage/.kodi/userdata/addon_data/docker.linuxserver.nginx/config/keys
    owner: root
    group: root
    mode: 0755

- name: Change permissions on certificates.
  file:
    path: '/storage/.kodi/userdata/addon_data/docker.linuxserver.nginx/config/keys/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'cert.crt'
    - 'cert.key'

- name: Copy proxy server
  template:
    src: proxy.j2
    dest: /storage/.kodi/userdata/addon_data/docker.linuxserver.nginx/config/nginx/site-confs/proxy
    owner: nobody
    group: users
    mode: 0664

- name: Add port 9090 to nginx container
  lineinfile:
    path: /storage/.kodi/addons/docker.linuxserver.nginx/bin/docker.linuxserver.nginx
    regexp: '_port":80'
    line: '           -p "$P_port":80 \'

- name: Start nginx
  service:
    name: docker.linuxserver.nginx.service
    state: restarted
