- name: Install Ansible Python 2 Dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-firewall
    - libselinux-python
    - libsemanage-python

- name: Ensure NFS utilities are installed.
  package:
    name: nfs-utils
    state: installed

- name: Allow services over firewall.
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    zone: internal
    immediate: yes
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: Disallow services over firewall.
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: disabled
    zone: internal
    immediate: yes
  with_items:
    - samba-client
    - ipp-client

- name: Move server into internal zone.
  firewalld:
    zone: internal
    interface: enp10s0f1
    permanent: true
    state: enabled

- name: Ensure rpcbind is running.
  service:
    name: rpcbind
    state: started
    enabled: yes

- name: Ensure directories to export exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"
  notify:
    - restart nfs

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports.d/storage.exports
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nfs

- name: Copy imapd file.
  template:
    src: idmapd.conf.j2
    dest: /etc/idmapd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nfs

- name: Copy hosts.allow file.
  template:
    src: hosts.allow.j2
    dest: /etc/hosts.allow
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nfs

- name: Ensure nfs is running.
  service:
    name: nfs-server
    state: started
    enabled: yes

- name: Install PowerPanel CyperPower UPS
  package:
    name: https://dl4jz3rbrsfum.cloudfront.net/software/powerpanel-132-0x86_64.rpm
    state: installed

- name: PowerPanel service is enabled
  service:
    name: pwrstatd
    state: started
    enabled: yes
